### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hmontenegro** [rajewsky-lab/mirdeep2#108]
There are some fixes in the installation process and in one or two scripts, it would be nice to have a release to pin them.

**Comment by mschilli87** [comment]
@Drmirdeep: See [here](https://github.com/rajewsky-lab/mirdeep2/compare/v0.1.3...master) for an overview of what changed since the last release. I'd like to fix/merge/close open issues and pull requests before doing a new release. Do you think you'll have time for a round of cleanup this year? I could take care of the release (incl. updating the GNU Guix package definition).

**Comment by mschilli87** [comment]
Maybe we can clean the issues then...
