### ISSUE TITLE
mirdeep2 randfold pvalues from two reference genomes for bos taurus 

### ISSUE THREAD

**Issue by mukiibi** [rajewsky-lab/mirdeep2#14]
Hi,
I am testing mirdeep2.pl on two reference bovine reference genomes (UMD3.1 and ARS-UCD1.2).
ARS-UCD1.2 is the most recently published bovine reference genome.
I get almost the same expressed mirRNAs with both references, however, with UMD3.1 some of the expressed mirRNAs have significant (yes) randfold p-values and some not significant (no). Surprisingly all expressed mirRNAs with ARS-UCD1.2 have thier randfold p-values not significant and non with a significant p-value.

Is this something you have observed before? Could it be something inherently related to the difference in the two genomes?
Thank you,
Robert

**Comment by Drmirdeep** [comment]
Hi Robert,
I have not seen this before but since this is randfold related it may be simply a normal result. 
To check this I would compare the precursor sequences where you get different results and see if has todo with that. Otherwise I would run randfold a few times on one of the significant candidates and see what the pvalue is.

Best  regards

**Comment by mukiibi** [comment]
Hi Marcel, I didnt manage to resolve this but I decided to use the results from UMD3.1 (the older reference) as the counts for the miRNAs were generally concordant

**Comment by mschilli87** [comment]
Closing as there is nothing to do - feel free to re-open if this turns out to be a miRDeep2 issue after all.
