### ISSUE TITLE
Illegal left brace in line 2680

### ISSUE THREAD

**Issue by OnlyHigh** [rajewsky-lab/mirdeep2#36]
Hi,
I'm getting the following error with my anaconda installation (with my data and with the ```run_tuto.sh```) 
This issue is similar than #13,
and there's report of this issue in other [repositories](https://bitbucket.org/cbbio/miarma/issues/112/de-novo-mirdeep2-problems-cannot-stat)
 
```
started: 16:16:56
make_html.pl -f mirdeep_runs/run_26_05_2019_t_16_16_10/output.mrd -p mirdeep_runs/run_26_05_2019_t_16_16_10/tmp/precursors.coords -v 0 -s mirdeep_runs/run_26_05_2019_t_16_16_10/survey.csv -c -e -r /home/bio/anaconda3/bin//../Rfam_for_miRDeep.fa -y 26_05_2019_t_16_16_10 -o  -V 2.0.0.8 

Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/option{ <-- HERE t}\s*=\s*(\S+)/ at /home/bio/anaconda3/bin/make_html.pl line 2680.

ended: 16:16:56
total:0h:0m:0s
```
Find attached the log file
[error-conda.log](https://github.com/rajewsky-lab/mirdeep2/files/3221109/error-conda.log)

Also I got a similar error with the installation via ```install.pl```, find attached
[error-installpl.log](https://github.com/rajewsky-lab/mirdeep2/files/3221107/error-installpl.log)
I installed the module via ```conda``` and ```cpan```

There's any solution for the issue? 
Cheers, 
Luis Alfonso.

**Comment by Drmirdeep** [comment]
Hi Luis, 
the issue is explained already in the reference #13 and since we are not maintaining the conda version I cannot really help. The github version is already more advanced, maybe an update conda version has it solved already. However, the leftbraces 'warning' message and the missing csv file may be actually two different issues. If you can provide a little working example with files that would be helpful to test. Otherwise have a look if the file mirdeep_runs/run_26_05_2019_t_16_16_10/survey.csv is present and not empty to.

Cheers,
Sebastian

**Comment by OnlyHigh** [comment]
```
miRDeep2 score	estimated signal-to-noise	excision gearing
10	0	1
9	0	1
8	0	1
7	0	1
6	0	1
5	0	1
4	0	1
3	0	1
2	0	1
1	0	1
0	0	1
-1	0	1
-2	0	1
-3	0	1
-4	0	1
-5	0	1
-6	0	1
-7	0	1
-8	0	1
-9	0	1
-10	0	1
```

That's the content of the ```survey.csv``` file 
where do I send the files?

**Comment by Drmirdeep** [comment]
Your file looks empty so I suspect the issues arise somewhere before. You are also missing the PDF::API2 package. Anyhow, I can only suggest to download the latest miRDeep2 release from git hub and run the install.pl. If running the tutorial then still gives warnings let us know. We cannot give support for the conda package since we did not provide it, plus it seems to use not the recent miRDeep2 release.

**Comment by OnlyHigh** [comment]
The PDF:API2 error was apparently raised for the conda and the ```install.pl``` version installed simultaneously.
