### ISSUE TITLE
miRDeep2.pl and mapper.pl input for novel species - one sample or all samples?

### ISSUE THREAD

**Issue by dansapozhnikov** [rajewsky-lab/mirdeep2#40]
Hi - just a simple question - for a novel species, am I right to believe I should merge reads from all the replicates and all my conditions when running the mapper.pl and miRDeep2.pl scripts in order to facilitate maximally effective miRNA discovery?
Thank you.

**Comment by Drmirdeep** [comment]
Hi, this is the issues thread for the miRDeep2 software. Apparently, there is no issue with the software and no question about how to run it. Maybe you can post you question on some analysis forum or just do some trial and error with different combinations. 
Best

**Comment by gygys** [comment]
That's not a threading issue. The question is whether there's a difference in miRNA discovery efficiency when running each sample individually compared to running all samples combined into one file.

**Comment by mschilli87** [comment]
@gygys: The point was that this is a bug tracker and there is no bug. This is not a general user support forum. Please use other channels to discuss such quesions amongst users instead of adressing it to developers only.

---
Regarding the qeustion: Personally, I tend to pool all samples for detection, filter the predicted miRNAs, merge the ones I believe to be real with the miRBase annotation and quantify per sample.

If you have more need to discuss, please use another channel instead of posting on a six year old bug report that was closed because it doesn't belong here.
