### ISSUE TITLE
mirdeep2.pl:-g parameter 

### ISSUE THREAD

**Issue by zhengyzh** [rajewsky-lab/mirdeep2#48]
I wonder why the -g default parameter is 50000.Can the -g parameter be set to - 1 directly, which will result in slow program operation or inaccurate prediction results?

**Comment by Drmirdeep** [comment]
The tool is 7 years old now. That's why. Technology is advancing fast. Use the -g switch to adjust the setting. If you have lots of data it may of course slow down the running time and even influence the results. -1 will look at all putative precursors not just the ones topX( default 50000) with highest read counts.

**Comment by zhengyzh** [comment]
Thank you for your reply.Is the parameter -g set to - 1 to cause bad or incorrect results, as opposed to setting topx?


------------------ 原始邮件 ------------------
发件人:&nbsp;"Sebastian Mackowiak"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月19日(星期四) 晚上6:29
收件人:&nbsp;"rajewsky-lab/mirdeep2"<mirdeep2@noreply.github.com&gt;;
抄送:&nbsp;"粞~"<550576990@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rajewsky-lab/mirdeep2] mirdeep2.pl:-g parameter  (#48)




The tool is 7 years old now. That's why. Technology is advancing fast. Use the -g switch to adjust the setting. If you have lots of data it may of course slow down the running time and even influence the results. -1 will look at all putative precursors not just the ones topX( default 50000) with highest read counts.

**Comment by mschilli87** [comment]
@zhengyzh:
> Is the parameter -g set to - 1 to cause bad or incorrect results, as opposed to setting topx?

@Drmirdeep wrote
>  -1 will look at all putative precursors not just the ones topX( default 50000) with highest read counts.

I think it is clearly stated what the parameter does.
If you don't know what behaviour you want, I recommend reading the paper, understanding how the tool you are using works, and making an educated decision based on yor scientif question.
Otherwise, I would recommend not using miRDeep2 at all.
This is not a discussion forum but a means to communicate (potential) bugs which you do not seem to encounter. For more genral help, I recommend [Biology SE](https://biology.stackexchange.com) ~and~ **or** [BioStars](https://www.biostars.org) (Please don't cross-post).
