### ISSUE TITLE
Illegal division by zero error by mapper.pl

### ISSUE THREAD

**Issue by VenithaB** [rajewsky-lab/mirdeep2#58]
I tried to use mapper.pl without collapsing reads in the following loop:

``` 
  for i ./*.fq 
  do
  name=$(echo "$i" | cut -f 9 -d '/' | cut -f 1 -d '.');
  echo "The file "$name" is now being converted to FASTA format";
  mapper.pl $i -e -h -j -p Triticum_aestivum -s mapper.pl_wo-collapsing_output/$name".fa" -t mapper.pl_wo-collapsing_output/$name".arf" -v -o 8;
  done
```

I am getting the following error:

```
The file 2_1_I_R1_trimmed is now being converted to FASTA format

parsing fastq to fasta format
discarding sequences with non-canonical letters
discarding short reads
mapping reads to genome index
trimming unmapped nts in the 3' ends
Log file for this run is in mapper_logs and called mapper.log_28784
Mapping statistics

#desc	total	mapped	unmapped	%mapped	%unmapped
total: 0	0	0	Illegal division by zero at /home/installations/mirdeep2/bin/mapper.pl line 737, <IN> line 165729.
```
Funnily enough, the processed reads and mapping file, .fa and .arf are output and are not empty.

I get the same error for all the .fq files in the directory (a total of 7), although the ```<IN> line``` differs for each. 

When I ran the same loop with the collapsed option, the mapping statistics were output fine.

**Comment by mschilli87** [comment]
@VenithaB:
> I tried to use mapper.pl without collapsing reads [...]

Why would you do this? To get the same results with longer runtime? :confused: 

> When I ran the same loop with the collapsed option, the mapping statistics were output fine.

Good. I don't really see a problem then. :wink: 

How would you like miRDeep2 to behave instead and why?
Do you suggest a note in the documentation that not collapsing reads before mapping is a bad idea and therefore not supported?
Do you think this "user error' should be caught and a trigger a more useful error message than `Illegal division by zero [...]`?

**Comment by VenithaB** [comment]
Hi! 

Actually my mapping percentage was very low and mistakenly understood collapsing to be a type of de-duplication. I had a hunch that's its to enhance performance, but I was not able to find any confirmation, even in the miRDeep2 paper. 

This is the first time I'm analyzing miRNA data. I think a note in the documentation would be a great addition for newbies like me! Collapsing reads by default with a switch to turn it off would be even better.

Thank you for your reply, you saved me a lot of confusion!

**Comment by mschilli87** [comment]
Just to have it documented. The 'collapsing' removes duplicate (identical!) reads keeping track of the count each distinct read was observed in the input data. Thus, each read (sequence) is mapped only once. For quantification, mappings statistics, etc., the numbers are 'inflated' back using the aforementioned counts.
This strategy can speed up RNA-seq processing in genreal but particularily for miRNA analyses as (ideally) all reads originating from the same miRNA will have the identical sequence (except for sequencing errors) as the miRNA should be sequence exactly end to end (which is why collapsing should to be done *after* adapter pruning). Also, in actual samples typically few miRNAs make up the majority of the overall pool, resulting in a large fraction of input reads collapsing to a much lower number of distinct reads without the loss of any (relevant) information.

---
@Drmirdeep: Feel free to update the documentation if you see the need. I'd hope this comment is enough for people to find it if they encounter this error. :wink:

---
@VenithaB:
> Collapsing reads by default with a switch to turn it off would be even better.

Changing the default behaviour of an established piece of software after several years doesn't sound like a good idea. Ask any non-newbie around you how their scripts broke when BEDTools switched the input order for `bedtools intersect` from one version to the next (with good intentions and improving the functionality by doing so). :wink:

**Comment by Drmirdeep** [comment]
Since it is unclear if the initial reads were adapter clipped or even would map properly I cannot comment on it. If they were not even clipped then nothing should map properly and the error message would make perfect sense. 
If you give us something at hands to reproduce the error then there would be a chance to debug it.

**Comment by VenithaB** [comment]
> If none of your reads mapped what kind of error message do you expect?
> You cannot divide by 0!
> The algorithm is described extensively in the papers.


Agreed, but my question also was about why the reads weren't being mapped without being collapsed, when they were mapped after being collapsed? I provided the exact same files.
