### ISSUE TITLE
miRNAseq read length in mirdeep2

### ISSUE THREAD

**Issue by shannjiang** [rajewsky-lab/mirdeep2#62]
Dear Sir or Madam,

I am trying to use mirdeep2 to call miRNA in my miRNAseq data. As I know the length of miRNAs is 20-25 bp, I noticed the read lengths of the reads in the tutorial toy .fasta file are around the same as the miRNA length, but in my case the read lengths in the miRNAseq are 50 bp always. Is that reasonable to have a read length in the miRNAseq almost double the size of the common miRNAs? If it is not, what makes the read length so long? Can the mirdeep2 call out miRNAs in miRNAseq with a read length so long?

thanks,

Shan

**Comment by mschilli87** [comment]
@shannjiang:
For technical reasons, the cDNA reverse-transcribed from the actual miRNA molecules is extended with 3' and 5' adapters. Typically, the 5' part is not sequenced, but since the shortest read length Illumina provides kits for is 50, oftentimes the reads consist of the miRNA sequence followed by the 5' end of the 3' adapter sequence.
It is possible to trim the reads before passing them to miRDeep2 (*e.g.* using [flexbar](https://github.com/seqan/flexbar), [trimmomatic](https://github.com/timflutre/trimmomatic), or [a similar tool](https://duckduckgo.com/?q=rna+seq+read+adapter+trimming+tool&ia=web)) or let miRDeep2 handle them (see the `-k` option in the [README](https://github.com/rajewsky-lab/mirdeep2/blob/master/README.md)).
If you don't know the adapter sequences used in the protocol that generated the data and can't find out, you can use tools like [fastp](https://github.com/OpenGene/fastp) or [FastQC](https://www.illumina.com/products/by-type/informatics-products/basespace-sequence-hub/apps/fastqc.html) to identify it.

**Comment by shannjiang** [comment]
Thank you, Marcel Schilling! It's really informative!


Shan


________________________________
