### ISSUE TITLE
Non-deterministic behaviour of miRDeep2 

### ISSUE THREAD

**Issue by Pfaendner** [rajewsky-lab/mirdeep2#66]
Hi all,

lately I am working a lot with miRDeep2 and especially with the script miRDeep2_core_algorithm.pl.
While running the script with the same input files and options, the generated output differed with respect to the number of potential precursors and the ordering of the read signature.

I think it would be a great improvement for your software to be deterministic and replicable.
To make your work easier I have sent a pull request #65 , proposing some changes.

What are your thoughts on this issue? I highly appreciate your feedback.

Best regards,

Christian Pfaendner

**Comment by Drmirdeep** [comment]
Hi, 
in general I am always in for reproducibility. However, the algorithm is of course not fully deterministic which starts already with the randfold steps involved in it. Furthermore, I would not want to decide what is the mature and star form in a miRNA in precursor when both have equal number of reads supporting it, especially when this number is very low (e.g. 2 or 3) . This is more a problem of small numbers when it comes to analysis and less a problem of non-deterministic behavior. 
Since there is no bug in here there is no reason to change the code. However, 
if you want fully deterministic behavior you could set the 
PERL_HASH_SEED variable before each perl script call to a predefined value. That should give reproducible behavior of perl's hash sort function.

**Comment by Pfaendner** [comment]
Hi,

thanks for your comprehensive and quick answer.
Actually, I am going to patch randfold as well, providing an option to set a seed and make it deterministic.

I understand that deciding upon the mature form in a potential precursor is difficult. For this very reason, I think it is even more important for us users to have a consistent and understandable way of choosing the mature form. The result would be a reliable and consistent output.
You're right, PERL_HASH_SEED is a possibility. However, its behaviour must not be preserved across different versions of perl and it is not very user friendly.

If you do not want to change the main pipeline of miRDeep2, what do you think about adding a command-line flag? I would provide all the implementation work, sending you pull-requests when the code is finished.

Best,

Christian Pfaendner
