### ISSUE TITLE
handling mature_precursor from quantifier.pl

### ISSUE THREAD

**Issue by waleadebayo** [rajewsky-lab/mirdeep2#78]
Hi , many thanks in advance
I have used mapper.pl and quantifier.pl on the collapsed. fa with output as below, 

![ssmr](https://user-images.githubusercontent.com/19531978/124350907-42d73980-dbef-11eb-8c74-b642f0e7fea0.png)

clearly two precursors of the same miR have similar counts, 
(a)if I don't want precursor info, Is summing up or averaging the best way to deal with this ? 
(b)can I stop this behaviour in quantifier.pl, i.e. exclude precursor info

**Comment by Drmirdeep** [comment]
Although I don't see any issue here we can easily resolve this.
If you used the weighing option in quantifier.pl you can sum up the read counts. Otherwise not. Just choose one of the precursors as your default. 

second option, just take out the double of triple occurring precursors from the input file.
There is no behavior to stop. It works exactly as intended.
